// <auto-generated />
using System;
using AppDeclaracion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDeclaracion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppDeclaracion.Domain.ActividadEmpresarial.DeduccionActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IngresoActividadEmpresarialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoActividadEmpresarialId");

                    b.ToTable("deducciones_actividad_empresarial", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.ActividadEmpresarial.IngresoActividadEmpresarial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("IngresosCobrados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagosProvisionalesRealizados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId")
                        .IsUnique();

                    b.ToTable("ingresos_actividad_empresarial", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Arrendamiento.DeduccionArrendamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IngresoArrendamientoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoArrendamientoId");

                    b.ToTable("deducciones_arrendamiento", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Arrendamiento.IngresoArrendamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("IngresosCobrados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagosProvisionalesRealizados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoDeduccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId")
                        .IsUnique();

                    b.ToTable("ingresos_arrendamiento", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Ejercicio")
                        .IsUnique();

                    b.ToTable("declaraciones_anuales", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.DeduccionPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId");

                    b.ToTable("deducciones_personales", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.ResultadoCalculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseGravableAcumulable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DeduccionesPersonalesAplicadas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("IngresoAcumulableTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IsrCausadoAcumulable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IsrResicoCausado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IsrResicoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagosAnticipadosAcumulable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId")
                        .IsUnique();

                    b.ToTable("resultados_calculo", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Resico.IngresoMensualResico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IngresoCobrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IngresoResicoId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("RetencionIsr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoResicoId");

                    b.ToTable("ingresos_mensuales_resico", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Resico.IngresoResico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId")
                        .IsUnique();

                    b.ToTable("ingresos_resico", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.SueldosYSalarios.IngresoSueldos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DeclaracionAnualId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("IngresoGravado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IsrRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionAnualId")
                        .IsUnique();

                    b.ToTable("ingresos_sueldos", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rfc")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.ActividadEmpresarial.DeduccionActividad", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.ActividadEmpresarial.IngresoActividadEmpresarial", null)
                        .WithMany("Deducciones")
                        .HasForeignKey("IngresoActividadEmpresarialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.ActividadEmpresarial.IngresoActividadEmpresarial", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithOne("IngresoActividadEmpresarial")
                        .HasForeignKey("AppDeclaracion.Domain.ActividadEmpresarial.IngresoActividadEmpresarial", "DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Arrendamiento.DeduccionArrendamiento", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Arrendamiento.IngresoArrendamiento", null)
                        .WithMany("Deducciones")
                        .HasForeignKey("IngresoArrendamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Arrendamiento.IngresoArrendamiento", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithOne("IngresoArrendamiento")
                        .HasForeignKey("AppDeclaracion.Domain.Arrendamiento.IngresoArrendamiento", "DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.DeduccionPersonal", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithMany("DeduccionesPersonales")
                        .HasForeignKey("DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.ResultadoCalculo", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithOne("Resultado")
                        .HasForeignKey("AppDeclaracion.Domain.Declaraciones.ResultadoCalculo", "DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Resico.IngresoMensualResico", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Resico.IngresoResico", null)
                        .WithMany("Meses")
                        .HasForeignKey("IngresoResicoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Resico.IngresoResico", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithOne("IngresoResico")
                        .HasForeignKey("AppDeclaracion.Domain.Resico.IngresoResico", "DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.SueldosYSalarios.IngresoSueldos", b =>
                {
                    b.HasOne("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", null)
                        .WithOne("IngresoSueldos")
                        .HasForeignKey("AppDeclaracion.Domain.SueldosYSalarios.IngresoSueldos", "DeclaracionAnualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AppDeclaracion.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AppDeclaracion.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDeclaracion.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AppDeclaracion.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppDeclaracion.Domain.ActividadEmpresarial.IngresoActividadEmpresarial", b =>
                {
                    b.Navigation("Deducciones");
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Arrendamiento.IngresoArrendamiento", b =>
                {
                    b.Navigation("Deducciones");
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Declaraciones.DeclaracionAnual", b =>
                {
                    b.Navigation("DeduccionesPersonales");

                    b.Navigation("IngresoActividadEmpresarial");

                    b.Navigation("IngresoArrendamiento");

                    b.Navigation("IngresoResico");

                    b.Navigation("IngresoSueldos");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("AppDeclaracion.Domain.Resico.IngresoResico", b =>
                {
                    b.Navigation("Meses");
                });
#pragma warning restore 612, 618
        }
    }
}
