<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>80a6e821-9d15-4180-b5e8-f769da79f9e5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppDeclaracion.Application\AppDeclaracion.Application.csproj" />
    <ProjectReference Include="..\AppDeclaracion.Domain\AppDeclaracion.Domain.csproj" />
    <ProjectReference Include="..\AppDeclaracion.Infrastructure\AppDeclaracion.Infrastructure.csproj" />
  </ItemGroup>

</Project>
